"""add candies.sender

Revision ID: 30644328aa61
Revises: 95c002ceffcc
Create Date: 2026-09-04 09:19:18.793080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '30644328aa61'
down_revision: Union[str, None] = '95c002ceffcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candies', sa.Column('sender', sa.String(length=12), nullable=True), schema='pumpkin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candies', 'sender', schema='pumpkin')
    # ### end Alembic commands ###
