"""init users baskets candies

Revision ID: 95c002ceffcc
Revises: 
Create Date: 2026-09-03 23:04:12.731956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '95c002ceffcc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_id', name='uq_users_provider'),
    schema='pumpkin'
    )
    op.create_table('baskets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=12), nullable=False),
    sa.Column('slug', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['pumpkin.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_baskets_user'),
    schema='pumpkin'
    )
    op.create_index(op.f('ix_pumpkin_baskets_slug'), 'baskets', ['slug'], unique=True, schema='pumpkin')
    op.create_table('candies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('basket_id', sa.UUID(), nullable=False),
    sa.Column('shell', sa.SmallInteger(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('curse_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(kind = 'letter' AND content IS NOT NULL AND curse_id IS NULL) OR (kind = 'curse' AND curse_id IS NOT NULL AND content IS NULL) OR (kind = 'plain' AND content IS NULL AND curse_id IS NULL)", name='ck_candies_payload'),
    sa.CheckConstraint("kind IN ('letter', 'curse', 'plain')", name='ck_candies_kind'),
    sa.CheckConstraint('shell >= 0 AND shell < 12', name='ck_candies_shell'),
    sa.ForeignKeyConstraint(['basket_id'], ['pumpkin.baskets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='pumpkin'
    )
    op.create_index('ix_candies_basket_created', 'candies', ['basket_id', 'created_at'], unique=False, schema='pumpkin')
    op.create_index('uq_candies_basket_curse', 'candies', ['basket_id', 'curse_id'], unique=True, schema='pumpkin', postgresql_where='curse_id IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_candies_basket_curse', table_name='candies', schema='pumpkin', postgresql_where='curse_id IS NOT NULL')
    op.drop_index('ix_candies_basket_created', table_name='candies', schema='pumpkin')
    op.drop_table('candies', schema='pumpkin')
    op.drop_index(op.f('ix_pumpkin_baskets_slug'), table_name='baskets', schema='pumpkin')
    op.drop_table('baskets', schema='pumpkin')
    op.drop_table('users', schema='pumpkin')
    # ### end Alembic commands ###
